[package]

name        = "nix_old"
description = "Rust friendly bindings to *nix APIs"
version     = "0.4.3"
authors     = ["Carl Lerche <me@carllerche.com>"]
homepage    = "https://github.com/carllerche/nix-rust"
license     = "MIT"
exclude     = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*"
]

[features]
eventfd = []
execvpe = []
preadv_pwritev = []
signalfd = []

[dependencies]
libc     = "0.1.12"
bitflags = "0.3.2"

[dev-dependencies]
rand = "0.3.8"

[dev-dependencies.nix-test]
path    = "nix-test"
version = "0.0.1"

[[test]]
name = "test"
path = "test/test.rs"

[[test]]
name = "test-signalfd"
path = "test/test_signalfd.rs"
harness = false
test = true
